### ISSUE TITLE
Display ID while searching user in visualizer

### ISSUE THREAD

**Issue by balcirakpeter** [CESNET/NextGenPerunGUI#151]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I search a user in visualizer (user-destination relationship) and there are more users with the same name.
It is not possible to recognize the right one.

**Describe the solution you'd like**
It would be nice to see some identification alongside with the user name in the list.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Vojtech-Sassmann** [comment]
Could you please provide a screenshot with illustrated desired changes?

**Comment by balcirakpeter** [comment]
![relationship](https://user-images.githubusercontent.com/17315935/65060701-ab9ce580-d978-11e9-9d06-e82d3c971a6c.png)

**Comment by Vojtech-Sassmann** [comment]
The IDs seems to be pretty large and distracting. Also, the position is pretty odd. Are you sure this is the way that would make you happy?

**Comment by Vojtech-Sassmann** [comment]
If it would be done this way, it would make me flustrated.

**Comment by Vojtech-Sassmann** [comment]
@stavamichal Could you please provide an external opinion?

**Comment by balcirakpeter** [comment]
It is just an illustration capturing the main concept. I believe your team can figure out details so the result will follow the main design.

**Comment by stavamichal** [comment]
Of corse I can. I think what would you feel is frustration, not flustration. I would have the same. Id should be used only optional. Maybe you can use logins or organizations instead. And definitely smaller font.

**Comment by Vojtech-Sassmann** [comment]
This problem will be resolved in the next release.

**Comment by balcirakpeter** [comment]
@xkureck thank you for assigning yourself to the issue. I am truly happy that someone takes it seriously.

**Comment by xkureck** [comment]
@balcirakpeter You are welcome.
