### ISSUE TITLE
Export data from any list of objects table to a standard format like CSV

### ISSUE THREAD

**Issue by stavamichal** [CESNET/NextGenPerunGUI#172]
**Problem:**
When I have opened window with the list objects (like Vo, Members of Vo, Groups etc.) and their attributes, I would like to export this list to be able to process it or send it.

**Possible solution:**
Add a new button to every such list of objects which will generate at least one type of standard format file with actual content of the list.

**Possible formats:**
CSV, JSON, XML, PDF etc. (at least one format should be plaintext)

**Comment by Vojtech-Sassmann** [comment]
Transferred to the new repo: https://github.com/CESNET/perun-web-apps/issues/10
