### ISSUE TITLE
Dialog is too big for viewport at setting new attributes

### ISSUE THREAD

**Issue by xkureck** [CESNET/NextGenPerunGUI#185]
When setting new attribute you can make the dialog too big for viewport. This could be easily fixed by making the dialog scrollable
![image](https://user-images.githubusercontent.com/32871167/67279538-7c274e80-f4cb-11e9-8f9f-0a948a164b0e.png)

**Comment by Vojtech-Sassmann** [comment]
* Transferred to the new repo: https://github.com/CESNET/perun-web-apps/issues/13
